version: '3.3'
services:
  chatbot:
    build:
      context: ./chatbot/
    ports:
      - "8080:8080"
      - "8081:8081"
  deepfake:
    build:
      context: ./deep-fake/
    ports: 
      - "8082:8080"
  publicwifiattacker:
    build:
      context: ./public-wifi/
      dockerfile: Dockerfile.attacker
    ports:
      - "3001:3001"
  publicwifivictim:
    build:
      context: ./public-wifi/
      dockerfile: Dockerfile.victim
    ports: 
      - "84:3000"
  nginxproxy:
    container_name: nginxProxy
    build:
      context: ./nginxProxy/
    ports: 
      - "80:80"
      - "443:443"
    volumes: 
      - ./sites/:/var/www/
      - ./proxy/:/etc/nginx/conf.d/:ro
